# Generated by Django 2.2 on 2020-12-28 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_created_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 29, 0, 43, 43, 831838)),
        ),
    ]
