# Generated by Django 2.2 on 2021-01-05 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201229_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 3, 9, 49, 364242)),
        ),
    ]
