# Generated by Django 2.2 on 2021-01-06 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210106_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 3, 7, 8, 271532)),
        ),
    ]
