# Generated by Django 2.2 on 2020-12-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 27, 19, 20, 54, 289789)),
        ),
    ]
